import os
from datetime import datetime, timezone

import structlog
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import Settings
from app.models.api_key import ApiKey
from app.models.organization import Organization

logger = structlog.get_logger()


class NginxManager:
    def __init__(self, settings: Settings):
        self.map_path = settings.nginx_map_path
        self.container_name = settings.nginx_container_name

    async def regenerate_map(self, db: AsyncSession) -> None:
        """Generate api_keys.map and write atomically."""
        stmt = (
            select(ApiKey.key, Organization.slug)
            .join(Organization, ApiKey.organization_id == Organization.id)
            .where(ApiKey.is_active == True)  # noqa: E712
            .where(Organization.is_active == True)  # noqa: E712
        )
        result = await db.execute(stmt)
        rows = result.fetchall()

        timestamp = datetime.now(timezone.utc).isoformat()
        lines = [
            "# Auto-generated by Observer Manager. DO NOT EDIT MANUALLY.",
            f"# Generated at: {timestamp}",
            "",
        ]
        for key, slug in rows:
            lines.append(f'"Bearer {key}" "{slug}";')

        content = "\n".join(lines) + "\n"

        tmp_path = self.map_path + ".tmp"
        try:
            os.makedirs(os.path.dirname(self.map_path), exist_ok=True)
            with open(tmp_path, "w") as f:
                f.write(content)
            os.rename(tmp_path, self.map_path)
            logger.info("nginx_map_written", path=self.map_path, key_count=len(rows))
        except Exception as exc:
            logger.error("nginx_map_write_failed", error=str(exc), path=self.map_path)
            raise

    async def reload_nginx(self) -> None:
        """Exec 'nginx -s reload' in the nginx container via Docker SDK."""
        import docker

        try:
            client = docker.from_env()
            container = client.containers.get(self.container_name)
            exit_code, output = container.exec_run("nginx -s reload")
            if exit_code == 0:
                logger.info(
                    "nginx_reloaded", container=self.container_name
                )
            else:
                logger.error(
                    "nginx_reload_failed",
                    container=self.container_name,
                    exit_code=exit_code,
                    output=output.decode() if output else "",
                )
                raise RuntimeError(
                    f"nginx reload failed with exit code {exit_code}: {output}"
                )
        except Exception as exc:
            logger.error(
                "nginx_reload_error", container=self.container_name, error=str(exc)
            )
            raise

    async def update_and_reload(self, db: AsyncSession) -> None:
        """Regenerate map and reload nginx."""
        await self.regenerate_map(db)
        await self.reload_nginx()
